<?php

namespace App\Services\Payment;

use App\Models\Subscription;
use App\Models\WebhookEvent;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

/**
 * Paytm implementation of PaymentGatewayInterface.
 *
 * API: https://securegw-stage.paytm.in (sandbox) | https://securegw.paytm.in (live)
 *
 * Auth model is unique among the gateways — there is NO Authorization
 * header. Instead, every request body is wrapped as:
 *
 *   {
 *     "head": { "signature": "{checksum}" },
 *     "body": { ... actual payload ... }
 *   }
 *
 * The checksum is computed by:
 *   1. Append a 4-char random salt to the JSON body string with "|".
 *   2. SHA-256 hash → 64 hex chars.
 *   3. Append the salt → 68 chars.
 *   4. AES-128-CBC encrypt with the merchant key (fixed IV, base64 output).
 *
 * Inbound (S2S callback) verification reverses the steps:
 *   1. Decrypt CHECKSUMHASH with the merchant key.
 *   2. Last 4 chars = salt; first 64 = expected hash.
 *   3. Sort callback params by key ascending, exclude CHECKSUMHASH and
 *      null values; concatenate values with "|".
 *   4. SHA-256 of that string + "|" + salt → must match expected hash.
 *
 * Order/verify flow:
 *   /order  → POST /theia/api/v1/initiateTransaction (returns txnToken)
 *   client  → buyer pays via Paytm SDK using txnToken
 *   /verify → POST /v3/order/status (resultCode === '01' = TXN_SUCCESS)
 *
 * Webhook = Paytm's S2S callback, NOT a separate channel:
 *   - Form-encoded body (NOT JSON) — application/x-www-form-urlencoded.
 *   - Verified with the same checksum scheme as outbound, decoded from
 *     the CHECKSUMHASH form field.
 *   - Payment events use TXNID for dedupe / event_id.
 *   - Refund events carry REFUNDID — same handler, different code path.
 *
 * Currency: INR only — Paytm is India-focused.
 *
 * Persistence model: gateway_metadata JSON.
 *   After createOrder:    {paytm_order_id, paytm_txn_token}
 *   After webhook (pay):  + {paytm_txn_id, paytm_bank_txn_id, paytm_payment_mode, paytm_status}
 *   After webhook (refund): + {paytm_refund_id, paytm_status: 'REFUND_SUCCESS'}
 *
 * Subscription lookup: by paytm_order_id stored in gateway_metadata.
 * The order_id is generated by us as `sub_{subscription_id}_{microtime}`
 * and echoed back by Paytm in the callback.
 */
class PaytmService implements PaymentGatewayInterface
{
    /** Paytm checksum AES-128-CBC fixed IV — per Paytm spec. */
    private const IV = '@@@@&&&&####$$$$';

    public function getSlug(): string
    {
        return 'paytm';
    }

    public function getName(): string
    {
        return 'Paytm';
    }

    public function isConfigured(): bool
    {
        return ! empty($this->mid())
            && ! empty($this->merchantKey())
            && ! empty($this->website())
            && ! empty($this->industryType())
            && ! empty($this->channelId());
    }

    /**
     * Initiate a Paytm transaction. Returns a txnToken Flutter passes
     * to the Paytm SDK to launch the in-app payment flow.
     *
     * @throws \RuntimeException when initiation fails or no txnToken returned.
     */
    public function createOrder(int $amountInPaise, array $metadata = []): array
    {
        if (! $this->isConfigured()) {
            throw new \RuntimeException('Paytm is not configured (mid / key / website / industry_type / channel_id).');
        }

        // Order id must be unique per merchant. Paytm enforces 50 char max.
        $subscriptionId = (string) ($metadata['subscription_id'] ?? '0');
        $orderId = 'sub_'.$subscriptionId.'_'.substr((string) (microtime(true) * 10000), -10);

        $body = [
            'requestType' => 'Payment',
            'mid' => $this->mid(),
            'websiteName' => $this->website(),
            'orderId' => $orderId,
            // callbackUrl can be left empty — Paytm uses the S2S callback
            // URL configured at merchant onboarding (admin panel).
            'callbackUrl' => '',
            'txnAmount' => [
                'value' => $this->formatAmount($amountInPaise),
                'currency' => 'INR',
            ],
            'userInfo' => [
                'custId' => (string) ($metadata['user_id'] ?? 'guest'),
            ],
        ];

        $bodyJson = json_encode($body);
        $signature = $this->generateSignature($bodyJson, $this->merchantKey());
        if ($signature === '') {
            throw new \RuntimeException('Paytm checksum generation failed.');
        }

        $url = $this->apiBase().'/theia/api/v1/initiateTransaction'
            .'?mid='.urlencode($this->mid())
            .'&orderId='.urlencode($orderId);

        $response = Http::withoutVerifying()
            ->acceptJson()
            ->post($url, [
                'body' => $body,
                'head' => ['signature' => $signature],
            ]);

        if (! $response->successful()) {
            throw new \RuntimeException(
                'Paytm initiateTransaction failed: '.$response->status().' '.$response->body(),
            );
        }

        $resp = $response->json();
        $resultStatus = (string) ($resp['body']['resultInfo']['resultStatus'] ?? 'F');
        $txnToken = (string) ($resp['body']['txnToken'] ?? '');

        if ($resultStatus !== 'S' || $txnToken === '') {
            $msg = (string) ($resp['body']['resultInfo']['resultMsg'] ?? 'unknown error');
            throw new \RuntimeException("Paytm initiate rejected: {$resultStatus} — {$msg}");
        }

        return [
            'paytm_order_id' => $orderId,
            'txn_token' => $txnToken,
            'mid' => (string) $this->mid(),
            'amount' => $this->formatAmount($amountInPaise),
            'currency' => 'INR',
            'channel_id' => (string) $this->channelId(),
            'industry_type' => (string) $this->industryType(),
            'website' => (string) $this->website(),
            'mode' => $this->mode(),
        ];
    }

    /**
     * Verify by polling Paytm's order status API. resultCode '01' is
     * TXN_SUCCESS (the merchant-facing success code; not the same as
     * the initiate API's 'S' resultStatus).
     */
    public function verifyPayment(array $data): bool
    {
        $orderId = (string) ($data['paytm_order_id'] ?? '');
        if ($orderId === '' || ! $this->isConfigured()) {
            return false;
        }

        $body = [
            'mid' => $this->mid(),
            'orderId' => $orderId,
        ];
        $bodyJson = json_encode($body);
        $signature = $this->generateSignature($bodyJson, $this->merchantKey());

        $response = Http::withoutVerifying()
            ->acceptJson()
            ->post($this->apiBase().'/v3/order/status', [
                'body' => $body,
                'head' => ['signature' => $signature],
            ]);

        if (! $response->successful()) {
            return false;
        }

        $resultCode = (string) $response->json('body.resultInfo.resultCode', '');

        return $resultCode === '01';
    }

    public function verifyValidationRules(): array
    {
        return [
            'paytm_order_id' => 'required|string|max:100',
        ];
    }

    public function applyOrderIdsToSubscription(Subscription $subscription, array $orderResponse): void
    {
        $existing = $subscription->gateway_metadata ?? [];
        $subscription->update([
            'gateway_metadata' => array_merge((array) $existing, [
                'paytm_order_id' => (string) ($orderResponse['paytm_order_id'] ?? ''),
                'paytm_txn_token' => (string) ($orderResponse['txn_token'] ?? ''),
            ]),
        ]);
    }

    public function applyVerifiedIdsToSubscription(Subscription $subscription, array $verifyData): void
    {
        // Verify path doesn't introduce new IDs — the txn_id arrives via
        // the S2S callback. Persist the order_id again as a safety
        // measure (idempotent).
        $existing = $subscription->gateway_metadata ?? [];
        if (! isset($existing['paytm_order_id']) && ! empty($verifyData['paytm_order_id'])) {
            $subscription->update([
                'gateway_metadata' => array_merge((array) $existing, [
                    'paytm_order_id' => (string) $verifyData['paytm_order_id'],
                ]),
            ]);
        }
    }

    /* ==================================================================
     |  Webhook (Paytm S2S callback)
     | ================================================================== */

    /**
     * Handle Paytm's server-to-server callback. Body is form-encoded.
     *
     * Required fields: ORDERID, CHECKSUMHASH, STATUS, plus TXNID
     * (payment) or REFUNDID (refund).
     *
     * Status values: TXN_SUCCESS, TXN_FAILURE, PENDING. We treat:
     *   TXN_SUCCESS + REFUNDID present → markRefunded
     *   TXN_SUCCESS                    → activate
     *   TXN_FAILURE                    → markFailed
     *   PENDING / other                → 200 ignored
     */
    public function handleWebhook(Request $request): JsonResponse
    {
        if (! $this->isConfigured()) {
            return response()->json(['error' => 'Paytm not configured.'], 503);
        }

        $params = $request->all();
        $checksumHash = (string) ($params['CHECKSUMHASH'] ?? '');

        if ($checksumHash === '') {
            return response()->json(['error' => 'Missing CHECKSUMHASH.'], 401);
        }

        if (! $this->verifyCallbackSignature($params, $this->merchantKey(), $checksumHash)) {
            Log::warning('Paytm webhook signature mismatch.', [
                'ip' => $request->ip(),
                'order_id' => (string) ($params['ORDERID'] ?? ''),
            ]);

            return response()->json(['error' => 'Invalid signature.'], 401);
        }

        $orderId = (string) ($params['ORDERID'] ?? '');
        $txnId = (string) ($params['TXNID'] ?? '');
        $refundId = (string) ($params['REFUNDID'] ?? '');
        $status = (string) ($params['STATUS'] ?? '');

        if ($orderId === '' || ($txnId === '' && $refundId === '')) {
            return response()->json(['error' => 'Missing required fields.'], 422);
        }

        // Refund events use REFUNDID; payment events use TXNID. Picking
        // the right one keeps dedupe correct when both fire for the
        // same subscription.
        $eventId = $refundId !== '' ? $refundId : $txnId;
        $eventType = $refundId !== '' ? 'REFUND.'.$status : 'PAYMENT.'.$status;

        try {
            WebhookEvent::create([
                'gateway' => $this->getSlug(),
                'event_id' => $eventId,
                'event_type' => $eventType,
                'status' => WebhookEvent::STATUS_PROCESSED,
                'payload' => $params,
            ]);
        } catch (\Throwable $e) {
            return response()->json(['status' => 'duplicate'], 200);
        }

        $subscription = Subscription::where('gateway', $this->getSlug())
            ->where('gateway_metadata->paytm_order_id', $orderId)
            ->first();

        if (! $subscription) {
            WebhookEvent::where('gateway', $this->getSlug())
                ->where('event_id', $eventId)
                ->update(['status' => WebhookEvent::STATUS_IGNORED]);

            return response()->json(['status' => 'ignored'], 200);
        }

        $activator = app(SubscriptionActivator::class);

        $outcome = match (true) {
            $refundId !== '' && $status === 'TXN_SUCCESS' => $this->processRefund($subscription, $params, $activator),
            $status === 'TXN_SUCCESS' => $this->processPayment($subscription, $params, $activator),
            $status === 'TXN_FAILURE' => $this->processFailure($subscription, $activator),
            default => 'ignored',
        };

        if ($outcome === 'ignored') {
            WebhookEvent::where('gateway', $this->getSlug())
                ->where('event_id', $eventId)
                ->update(['status' => WebhookEvent::STATUS_IGNORED]);
        }

        return response()->json(['status' => $outcome], 200);
    }

    private function processPayment(Subscription $subscription, array $params, SubscriptionActivator $activator): string
    {
        $existing = $subscription->gateway_metadata ?? [];
        $subscription->update([
            'gateway_metadata' => array_merge((array) $existing, [
                'paytm_txn_id' => (string) ($params['TXNID'] ?? ''),
                'paytm_bank_txn_id' => (string) ($params['BANKTXNID'] ?? ''),
                'paytm_payment_mode' => (string) ($params['PAYMENTMODE'] ?? ''),
                'paytm_status' => 'TXN_SUCCESS',
            ]),
        ]);

        $activator->activate($subscription);

        return 'processed';
    }

    private function processFailure(Subscription $subscription, SubscriptionActivator $activator): string
    {
        $activator->markFailed($subscription);

        return 'processed';
    }

    private function processRefund(Subscription $subscription, array $params, SubscriptionActivator $activator): string
    {
        $existing = $subscription->gateway_metadata ?? [];
        $subscription->update([
            'gateway_metadata' => array_merge((array) $existing, [
                'paytm_refund_id' => (string) ($params['REFUNDID'] ?? ''),
                'paytm_status' => 'REFUND_SUCCESS',
            ]),
        ]);

        $activator->markRefunded($subscription);

        return 'processed';
    }

    /* ==================================================================
     |  Checksum math
     | ================================================================== */

    /**
     * Generate a Paytm signature for a JSON body string. Used for
     * outbound API calls (initiate, status, refund).
     *
     * Public so tests can use the SAME algorithm to forge valid
     * inbound checksums for the webhook handler.
     */
    public function generateSignature(string $body, string $key): string
    {
        $salt = $this->randomSalt(4);
        $hash = hash('sha256', $body.'|'.$salt);
        $cipher = openssl_encrypt($hash.$salt, 'AES-128-CBC', $key, 0, self::IV);

        return $cipher === false ? '' : $cipher;
    }

    /**
     * Verify a Paytm callback signature. Reverses the encryption to
     * extract the salt, then re-computes the SHA-256 hash from the
     * sorted, pipe-joined values and compares.
     *
     * Public so tests can also use it as a sanity check.
     */
    public function verifyCallbackSignature(array $params, string $key, string $checksumHash): bool
    {
        $decrypted = openssl_decrypt($checksumHash, 'AES-128-CBC', $key, 0, self::IV);
        if ($decrypted === false || strlen($decrypted) < 5) {
            return false;
        }

        $salt = substr($decrypted, -4);
        $expectedHash = substr($decrypted, 0, -4);

        $string = $this->buildCallbackString($params);
        $computedHash = hash('sha256', $string.'|'.$salt);

        return hash_equals($expectedHash, $computedHash);
    }

    /**
     * Build the canonical string that goes into the callback hash:
     * params sorted alphabetically by key, CHECKSUMHASH excluded,
     * null/'null' values dropped, values joined by '|'.
     *
     * Public for test-helper use (so the test fixture can sign a
     * fabricated callback exactly the way Paytm signs the real one).
     */
    public function buildCallbackString(array $params): string
    {
        unset($params['CHECKSUMHASH']);
        ksort($params);

        $values = [];
        foreach ($params as $value) {
            if ($value === null || $value === 'null') {
                continue;
            }
            $values[] = (string) $value;
        }

        return implode('|', $values);
    }

    private function randomSalt(int $length): string
    {
        // Hex chars only — Paytm's reference impl uses alphanumerics, but
        // hex is a safe subset and avoids encoding edge cases.
        return substr(bin2hex(random_bytes(max(2, $length))), 0, $length);
    }

    /* ==================================================================
     |  Internals
     | ================================================================== */

    private function mid(): ?string
    {
        return config('services.paytm.mid');
    }

    private function merchantKey(): ?string
    {
        return config('services.paytm.key');
    }

    private function website(): ?string
    {
        return config('services.paytm.website');
    }

    private function industryType(): ?string
    {
        return config('services.paytm.industry_type');
    }

    private function channelId(): ?string
    {
        return config('services.paytm.channel_id');
    }

    private function mode(): string
    {
        return config('services.paytm.mode') === 'production' ? 'production' : 'sandbox';
    }

    private function apiBase(): string
    {
        return $this->mode() === 'production'
            ? 'https://securegw.paytm.in'
            : 'https://securegw-stage.paytm.in';
    }

    /**
     * Convert paise → "9.99" — Paytm wants the value as a 2-decimal
     * string in major units.
     */
    private function formatAmount(int $amountInPaise): string
    {
        return number_format($amountInPaise / 100, 2, '.', '');
    }
}
