<?php

return [
    'height_list' => [
        '134 cm - 4 ft 05 inch', '135 cm', '136 cm', '137 cm - 4 ft 06 inch', '138 cm', '139 cm', '140 cm - 4 ft 07 inch',
        '141 cm', '142 cm - 4 ft 08 inch', '143 cm', '144 cm - 4 ft 09 inch', '145 cm', '146 cm', '147 cm - 4 ft 10 inch',
        '148 cm', '149 cm', '150 cm - 4 ft 11 inch', '151 cm', '152 cm - 5 ft 00 inch', '153 cm', '154 cm - 5 ft 01 inch',
        '155 cm', '156 cm', '157 cm - 5 ft 02 inch', '158 cm', '159 cm', '160 cm - 5 ft 03 inch', '161 cm', '162 cm - 5 ft 04 inch',
        '163 cm', '164 cm', '165 cm - 5 ft 05 inch', '166 cm', '167 cm - 5 ft 06 inch', '168 cm', '169 cm', '170 cm - 5 ft 07 inch',
        '171 cm', '172 cm - 5 ft 08 inch', '173 cm', '174 cm', '175 cm - 5 ft 09 inch', '176 cm', '177 cm - 5 ft 10 inch',
        '178 cm', '179 cm', '180 cm - 5 ft 11 inch', '181 cm', '182 cm', '183 cm - 6 ft 00 inch', '184 cm', '185 cm - 6 ft 01 inch',
        '186 cm', '187 cm', '188 cm - 6 ft 02 inch', '189 cm', '190 cm', '191 cm - 6 ft 03 inch', '192 cm', '193 cm - 6 ft 04 inch',
        '194 cm', '195 cm', '196 cm - 6 ft 05 inch', '197 cm', '198 cm - 6 ft 06 inch', '199 cm', '200 cm - 6 ft 07 inch',
        '201 cm', '202 cm', '203 cm - 6 ft 08 inch', '204 cm', '205 cm', '206 cm - 6 ft 09 inch', '207 cm', '208 cm - 6 ft 10 inch',
        '209 cm', '210 cm', '211 cm - 6 ft 11 inch', '212 cm', '213 cm - 7 ft 00 inch',
    ],

    'weight_list' => [
        '40 Kg', '41 Kg', '42 Kg', '43 Kg', '44 Kg', '45 Kg', '46 Kg', '47 Kg', '48 Kg', '49 Kg',
        '50 Kg', '51 Kg', '52 Kg', '53 Kg', '54 Kg', '55 Kg', '56 Kg', '57 Kg', '58 Kg', '59 Kg',
        '60 Kg', '61 Kg', '62 Kg', '63 Kg', '64 Kg', '65 Kg', '66 Kg', '67 Kg', '68 Kg', '69 Kg',
        '70 Kg', '71 Kg', '72 Kg', '73 Kg', '74 Kg', '75 Kg', '76 Kg', '77 Kg', '78 Kg', '79 Kg',
        '80 Kg', '81 Kg', '82 Kg', '83 Kg', '84 Kg', '85 Kg', '86 Kg', '87 Kg', '88 Kg', '89 Kg',
        '90 Kg', '91 Kg', '92 Kg', '93 Kg', '94 Kg', '95 Kg', '96 Kg', '97 Kg', '98 Kg', '99 Kg',
        '100 Kg', '101 Kg', '102 Kg', '103 Kg', '104 Kg', '105 Kg', '106 Kg', '107 Kg', '108 Kg', '109 Kg',
        '110 Kg', '111 Kg', '112 Kg', '113 Kg', '114 Kg', '115 Kg', '116 Kg', '117 Kg', '118 Kg', '119 Kg',
        '120 Kg', '121 Kg', '122 Kg', '123 Kg', '124 Kg', '125 Kg', '126 Kg', '127 Kg', '128 Kg', '129 Kg',
        '130 Kg', '131 Kg', '132 Kg', '133 Kg', '134 Kg', '135 Kg', '136 Kg', '137 Kg', '138 Kg', '139 Kg',
        '140 Kg', '140+ Kg', 'Prefer Not to Say',
    ],

    'annual_income_list' => [
        'Upto 1 Lakh', '1 Lakh To 2 Lakh', '2 To 3 Lakh', '3 To 4 Lakh', '4 To 5 Lakh',
        '5 To 6 Lakh', '6 To 7 Lakh', '7 To 8 Lakh', '8 To 9 Lakh', '9 To 10 Lakh',
        '10 To 12 Lakhs', '12 To 14 Lakhs', '14 To 16 Lakh', '16 To 18 Lakh', '18 To 20 Lakh',
        '20 To 25 Lakh', '25 To 30 Lakh', '30 To 35 Lakh', '35 To 40 Lakh', '40 To 45 Lakh',
        '45 To 50 Lakh', '50 To 60 Lakh', '60 To 70 Lakh', '70 To 80 Lakh', '80 To 90 Lakh',
        '90 To 1 Crore', '1 Crore And More', 'Prefer Not to Say',
    ],

    'country_list' => [
        'Frequently Used' => [
            'India', 'USA', 'UAE', 'United Kingdom', 'Canada', 'Australia', 'Saudi Arabia',
            'Qatar', 'New Zealand', 'Oman', 'Singapore', 'Switzerland', 'Bahrain', 'France',
            'Germany', 'Ireland', 'Italy', 'Kuwait', 'Malta',
        ],
        'Other Countries' => [
            'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Austria', 'Azerbaijan',
            'Bahamas', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina',
            'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Central African Republic',
            'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic',
            'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'East Timor', 'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea',
            'Estonia', 'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'Gabon', 'Gambia', 'Georgia', 'Ghana', 'Greece', 'Grenada', 'Guatemala',
            'Guinea', 'Guyana', 'Haiti', 'Honduras', 'Hungary', 'Iceland', 'Indonesia', 'Iran', 'Iraq', 'Israel', 'Ivory Coast',
            'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Korea, North', 'Korea, South', 'Kosovo', 'Kyrgyzstan',
            'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi',
            'Malaysia', 'Maldives', 'Mali', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia', 'Moldova', 'Monaco', 'Mongolia',
            'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'Nicaragua', 'Niger', 'Nigeria',
            'North Macedonia', 'Norway', 'Pakistan', 'Palau', 'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines',
            'Poland', 'Portugal', 'Romania', 'Russia', 'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Vincent and the Grenadines',
            'Samoa', 'San Marino', 'Sao Tome and Principe', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Slovakia', 'Slovenia',
            'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Syria',
            'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
            'Tuvalu', 'Uganda', 'Ukraine', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Vatican City', 'Venezuela', 'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe',
        ],
    ],

    'denomination_list' => [
        'Catholic' => [
            'Syrian Catholic', 'Latin Catholic', 'Malankara Catholic', 'Anglo Indian',
            'Knanaya Catholic', 'Nadar Christian', 'Cheramar Christian',
        ],
        'Non-Catholic' => [
            'Jacobite', 'Orthodox', 'Marthomite', 'CSI Christian', 'Knanaya Jacobite',
            'Chaldean Christian', 'Malabar Independent Syrian Church', 'Anglican Church of India',
            'Pentecostal', 'Brethren', 'Protestant', 'Evangelist', 'Salvation Army', 'Other',
        ],
    ],

    'diocese_list' => [
        'Adilabad', 'Agartala', 'Agra', 'Ahmedabad', 'Aizawl', 'Ajmer', 'Allahabad', 'Alleppey', 'Ambikapur', 'Amravati', 'Asansol', 'Aurangabad',
        'Bagdogra', 'Balasore', 'Bangalore', 'Bareilly', 'Baroda', 'Baruipur', 'Battery', 'Belgaum', 'Bellary', 'Belthangady', 'Berhampur', 'Bettiah',
        'Bhagalpur', 'Bhopal', 'Bijnor', 'Bombay', 'Bongaigaon', 'Calcutta', 'Calicut', 'Chanda', 'Changanacherry', 'Chengalpattu', 'Chennai-Mylapore',
        'Chickmagalur', 'Chingleput', 'Cochin', 'Coimbatore', 'Cuddapah', 'Cuttack-Bhubaneswar', 'Daltonganj', 'Darjeeling', 'Delhi', 'Dharmapuri',
        'Dibrugarh', 'Diphu', 'Dumka', 'Durgapur', 'Eluru', 'Ernakulam-Angamaly', 'Faridabad', 'Gandhinagar', 'Gangtok', 'Goa and Daman', 'Gorakhpur',
        'Gulbarga', 'Guntur', 'Guwahati', 'Gwalior', 'Hazaribag', 'Hyderabad', 'Idukki', 'Imphal', 'Indore', 'Irinjalakuda', 'Itanagar', 'Jabalpur',
        'Jaipur', 'Jalandhar', 'Jalpaiguri', 'Jammu-Srinagar', 'Jamshedpur', 'Jhansi', 'Jhabua', 'Jodhpur', 'Kalyan', 'Kanjirapally', 'Kannur', 'Karwar',
        'Khammam', 'Khandwa', 'Khunti', 'Kohima', 'Kothamangalam', 'Kottapuram', 'Kottar', 'Kottayam', 'Krishnagar', 'Kumbakonam', 'Kurnool', 'Lucknow',
        'Madurai', 'Mananthavady', 'Mangalore', 'Mavelikara', 'Meerut', 'Miao', 'Muzaffarpur', 'Mysore', 'Nagpur', 'Nalgonda', 'Nashik', 'Nellore',
        'Neyyattinkara', 'Nongstoin', 'Ootacamund', 'Palai', 'Palayamkottai', 'Palghat', 'Parassala', 'Pathanamthitta', 'Patna', 'Pondicherry and Cuddalore',
        'Poona', 'Port Blair', 'Punalur', 'Pune', 'Purnea', 'Quilon', 'Raiganj', 'Raigarh', 'Raipur', 'Rajkot', 'Ranchi', 'Rourkela', 'Sagar', 'Salem',
        'Sambalpur', 'Satna', 'Shillong', 'Shimoga', 'Silchar', 'Simdega', 'Sivagangai', 'Srikakulam', 'Sultanpet', 'Surat', 'Syro-Malankara', 'Tezpur',
        'Thamarassery', 'Thanjavur', 'Thuckalay', 'Tiruchirapalli', 'Tiruvalla', 'Trichur', 'Trivandrum', 'Tura', 'Tuticorin', 'Udaipur', 'Udupi', 'Ujjain',
        'Varanasi', 'Vellore', 'Verapoly', 'Vijayapuram', 'Vijayawada', 'Visakhapatnam', 'Warangal', 'Other',
    ],

    'caste_list' => [
        'Brahmin', 'Nair', 'Ezhava', 'Thiyya', 'Vishwakarma', 'Vokkaliga', 'Lingayat', 'Bunt', 'Billava', 'Devadiga', 'Mogaveera',
        'Kulal', 'Ganiga', 'Padmashali', 'Reddy', 'Naidu', 'Kamma', 'Kapu', 'Chettiar', 'Mudaliar', 'Gounder', 'Vanniyar', 'Nadar',
        'Yadav', 'Rajput', 'Kayastha', 'Maratha', 'Agarwal', 'Bania', 'Jat', 'SC', 'ST', 'Other',
    ],

    'sub_caste_list' => [
        'Shetty', 'Hegde', 'Rai', 'Poojary', 'Nayak', 'Amin', 'Karkera', 'Salian', 'Puthran', 'Suvarna', 'Kotian', 'Bangera',
        'Moolya', 'Kulal', 'Acharya', 'Kammara', 'Kansara', 'Shilpi', 'Menon', 'Pillai', 'Kurup', 'Nambiar', 'Iyer', 'Iyengar',
        'Gaud Saraswat Brahmin (GSB)', 'Havyaka', 'Shivalli', 'Kota', 'Other',
    ],

    'rasi_list' => [
        'Aries (Medam)', 'Taurus (Edavam)', 'Gemini (Midhunam)', 'Cancer (Karkidakam)', 'Leo (Chingam)', 'Virgo (Kanni)',
        'Libra (Thulam)', 'Scorpio (Vrishchikam)', 'Sagittarius (Dhanu)', 'Capricorn (Makaram)', 'Aquarius (Kumbham)', 'Pisces (Meenam)',
    ],

    'nakshatra_list' => [
        'Ashwini (Aswathy)', 'Bharani', 'Krittika (Karthika)', 'Rohini', 'Mrigashira (Makayiram)', 'Ardra (Thiruvathira)',
        'Punarvasu (Punartham)', 'Pushya (Pooyam)', 'Ashlesha (Ayilyam)', 'Magha (Makam)', 'Purva Phalguni (Pooram)',
        'Uttara Phalguni (Uthram)', 'Hasta (Atham)', 'Chitra (Chithira)', 'Swati (Chothi)', 'Vishakha (Vishakam)',
        'Anuradha (Anizham)', 'Jyeshtha (Thrikketta)', 'Mula (Moolam)', 'Purva Ashadha (Pooradam)', 'Uttara Ashadha (Uthradam)',
        'Shravana (Thiruvonam)', 'Dhanishta (Avittam)', 'Shatabhisha (Chathayam)', 'Purva Bhadrapada (Pooruruttathi)',
        'Uttara Bhadrapada (Uthruttathi)', 'Revati',
    ],

    'gothram_list' => [
        'Atri', 'Bharadvaja', 'Bhrigu', 'Gautam', 'Jamadagni', 'Kashyapa', 'Vasishta', 'Viswamitra', 'Agastya', 'Harita',
        'Kaundinya', 'Koushika', 'Moudgalya', 'Sandilya', 'Srivatsa', "Don't Know", 'Other',
    ],

    'educational_qualifications_list' => [
        '1. Audiology' => ['B.ASLP', 'B.Sc Audiology', 'Diploma In Audiology', 'M.Sc Audiology'],
        '2. Bachelors - Arts/Science/Commerce' => [
            'BA', 'BA Animation', 'Bachelor of Journalism', 'B.Com', 'BFA', 'BFSc', 'BFT', 'BHM', 'BJMC', 'BLIS',
            'B.Lit.', 'BMM', 'B.Mus', 'BOT', 'B.Phil', 'B.Sc', 'B.Sc Agriculture', 'B.Sc Animation', 'B.Sc (Hons.)',
            'B.Sc in Medical Lab Science', 'BSCJ', 'B.Sc Optometry', 'B.Sc Radiology and Imaging Technology',
            'B.Sc Respiratory Therapy', 'BSW', 'Degree in Therapy',
        ],
        '3. Bachelors - Engineering/Computers' => [
            'Aeronautical Engineering', 'AET', 'B.Arch', 'BCA', 'BCS', 'BE/B.Tech', 'B.Eng (Hons)', 'Biomedical Engineering',
            'B.Plan', 'B.Sc IT/Computer Science', 'B.S (Engineering)', 'B.Tech Food Technology', 'Chemical Engineering',
            'Civil Engineering', 'Electronics and Biomedical Engineering', 'Electronics and Communication Engineering',
            'Electronics and Electrical Engineering', 'Marine Engineering', 'Mechanical Engineering',
        ],
        '4. Bachelors - Medical/Dental' => ['BAMS', 'BDS', 'BHMS', 'BNYS', 'BSMS', 'BUMS', 'BVSc', 'DNB', 'MBBS'],
        '5. Bachelors - Management' => [
            'BBA', 'BBE', 'BBI', 'BBM', 'BFM (Financial Management)', 'BHA/BHM (Hospital Administration)',
            'BHM (Hotel Management)', 'BHRM', 'BMS', 'BSM', 'BTS (Tourism Studies)', 'BTTM', 'B.VOC', 'Other Degree in Management',
        ],
        '6. Certified Courses' => ['CCNA', 'CCNP', 'MCSE', 'QA/QC Engineering', 'RHCE', 'Software Testing'],
        '7. Design' => ['B.Des', 'B.Sc Multimedia', 'DCA', 'Diploma in Interior Designing', 'Graphic Design', 'M.Des'],
        '8. Diploma' => [
            'Business Management', 'D.Ed', 'D.EL.ED', 'Diploma', 'Diploma in Engineering', 'Diploma in Fashion Designing',
            'Diploma in Fire and Safety', 'Diploma in Instrumental Music', 'Diploma in Therapy', 'Diploma in Vocal Music',
            'Event Management', 'HDC', 'ITI/ITC', 'PGDCA', 'PG Diploma', 'Polytechnic', 'Trade School',
        ],
        '9. Finance - CA/CS/Others' => [
            'ACCA', 'ACS', 'Actuarial science', 'B.Sc/BF Finance', 'CA', 'CFA', 'CMA', 'CPA', 'CS', 'ICWA',
            'Master of Professional Accounting',
        ],
        '10. Higher Secondary/Secondary' => ['Higher Secondary School', 'High School', 'Under SSLC'],
        '11. Legal' => ['ALA', 'BGL/BL/LLB', 'ML/LLM'],
        '12. Masters - Arts/Science/Commerce' => [
            'MA', 'MA Animation', 'Master in Media and Mass Communication', 'Master of Journalism',
            'Master of Public Administration', 'Master of Public Health', 'Masters in International Security',
            'Masters of Population Studies', 'M.Com', 'MFA', 'MFSc', 'MJMC', 'M.Lib.I.Sc', 'MLIS',
            'M.Sc', 'M.Sc Agriculture', 'M.Sc Animation', 'M.Sc Horticulture', 'M.Sc Optical Technologies', 'MSW', 'MVA',
        ],
        '13. Masters - Engineering/Computer' => [
            'M.Arch', 'MCA', 'ME/M.Tech', 'M.Eng (Hons)', 'M.Plan', 'MS', 'M.Sc IT/Computer Science', 'MS(Engg.)', 'M.Tech',
        ],
        '14. Masters - Medical/Dental' => ['MCh', 'MD/MS (Medical)', 'MDS', 'MVSc'],
        '15. Masters - Management' => [
            'Master of Business Information Systems', 'Master of Computer Management', 'Master of Tourism Administration',
            'Masters in Energy Management', 'MBA/PGDM', 'MFM (Fashion Management)', 'MFM (Financial Management)',
            'MHA/MHM (Hospital Administration)', 'MHM (Hotel Management)', 'MHRM', 'MIB',
            'Post Graduate Diploma in Rural Management',
        ],
        '16. Nursing' => ['ANM', 'B.Sc Nursing', 'Diploma In Ayurvedic Nursing', 'General Nursing', 'M.Sc Nursing'],
        '17. Pharmacy' => ['B.Pharm', 'BPT', 'D.Pharm', 'MLT', 'M.Pharm', 'MPT', 'Pharm.D'],
        '18. Research' => ['JRF', 'M.Phil', 'PhD'],
        '19. Service - IAS/IPS/IES/IFS' => ['IAS', 'IES', 'IFS', 'IPS', 'IRS'],
        '20. Teaching' => ['B.Ed', 'CTET', 'K-TET', 'M.Ed', 'M.P.Ed (Physical Education)', 'NET', 'SET', 'TTC'],
    ],

    'occupation_category_list' => [
        '1. Admin' => [
            'Administrative Professional', 'Clerk', 'Corporate communication', 'Corporate Planning', 'Executive',
            'HR Executive', 'HR Manager', 'Manager', 'Officer', 'Operations management', 'Supervisors', 'Team Lead',
        ],
        '2. Agriculture' => ['Agriculture & Farming Professional', 'Farm Manager'],
        '3. Airline' => ['Air Hostess', 'Air Traffic Controller', 'Aircraft mechanic', 'Airline Professional', 'Airport executive', 'Cabin Crew', 'Pilot'],
        '4. Architect & Design' => ['Architect', 'Draftman', 'Interior Designer', 'Sculpturist'],
        '5. Banking & Accounts' => [
            'Accounts/Finance Professional', 'Auditor', 'Bank Manager/Asst. Manager', 'Banking Service Professional',
            'Cashier', 'Chartered Accountant', 'Chartered Financial Analyst', 'Company Secretary', 'Cost Accountant',
        ],
        '6. Beauty & Fashion' => ['Beautician', 'Fashion Designer', 'Make up Artist', 'Modeling'],
        '7. Below Graduate' => [
            'Agriculture (Occupation)', 'Bus Conductor', 'Carpenter', 'Computer Operator', 'Driver', 'Electrician', 'Fishermen',
            'Mason', 'Mechanic', 'Office staff', 'Oil & Gas Professional', 'Operator', 'Peon', 'Physical Trainer', 'Plumber',
            'Safety Officer', 'Security Guard', 'Singer', 'Skilled Worker', 'Srank', 'Store Manager', 'Sweeper', 'Tailor',
            'Tele Caller', 'Visual Communication Designer', 'Welder',
        ],
        '8. Education' => [
            'Academic Counsellor', 'Education Professional', 'Professor/Lecturer', 'Student Counsellor', 'Teaching/Academician', 'Tutor',
        ],
        '9. Hospitality' => ['Chef', 'Event planner', 'Hotel/ Hospitality Professional', 'Restaurant/Catering Professional'],
        '10. IT & Engineering' => [
            'Aeronautical Engineer', 'Biomedical Engineer', 'Chemical Engineer', 'Civil Engineer', 'Cyber/Network Security',
            'Data Analyst', 'Data Scientist', 'Electronics/Telecom Engineer', 'Engineer', 'Engineer Non IT',
            'Hardware Professional', 'Mechanical/Production Engineer', 'Network Engineer', 'Product Manager - IT',
            'Project Manager - IT', 'Software Consultant', 'Software Professional', 'UI/UX Designer', 'UX Writer', 'Web Designer',
        ],
        '11. Legal' => ['Corporate Lawyer', 'Judicial Services', 'Lawyer & Legal Professional', 'Legal Company Secretary', 'Legal Officer'],
        '12. Marketing & Sales' => ['Digital Marketer', 'Investment Professional', 'Marketing Professional', 'Product manager - Non IT', 'Sales Professional'],
        '13. Media & Entertainment' => [
            '3D/VFX Animator', 'Actor/Actress', 'Advertising/PR Professional', 'Anchor', 'Entertainment Professional',
            'Event Management Professional', 'Graphic Designer', 'Industrial Designer', 'Journalist', 'Media Professional', 'Videographer/Photographer',
        ],
        '14. Medical' => [
            'Allopathic Doctor', 'Audiologist', 'Ayurvedic Doctor', 'CT Technician', 'Dentist', 'Dietitian', 'Health Care Assistant',
            'Homeo Doctor', 'Laboratory Technician', 'Medical Coder', 'Medical Representative', 'Medical Transcription',
            'Microbiologist', 'MRI Technician', 'Naturopathic Doctor', 'Nutritionist', 'Occupational Therapist', 'Optometrist',
            'Paramedical Professional', 'Perfusionists', 'PG Doctors / Surgeons', 'Pharmacist', 'Physician Assistant',
            'Physiotherapist', 'Psychologist', 'Radiologist', 'Therapist', 'Veterinary Doctor', 'Xray Technician',
        ],
        '15. Merchant Navy' => ['Mariner/Merchant Navy'],
        '16. Nurse' => ['B.Sc Nurse', 'General Nurse', 'M.Sc Nurse', 'Nursing Assistance', 'Nursing Tutor'],
        '17. Others' => [
            'Analyst', 'Arts & Craftsman', 'Associate', 'BPO/KPO/ITES Professional', 'Business', 'Business Analyst',
            'Business Development Professional', 'Captain Central Gov.', 'Chemist', 'Construction Work', 'Consultant',
            'Content writer', 'Contractor', 'Coordinator', 'Counselor', 'Customer Care Professional', 'Deacon',
            'Fitness Professional', 'Freelancer', 'Insurance agent', 'Internship', 'Librarian', 'Loco Pilot',
            'Logistics Operations', 'Merchandiser', 'Non Teaching', 'Not Working', 'Part Time Job', 'Politician',
            'Priest', 'Project Manager - Non IT', 'Quality Controller', 'Receptionist', 'Sailor', 'Self Employed',
            'Social Worker', 'Sports Trainer', 'Sportsman', 'Student', 'Surveyor', 'Technician', 'Trader', 'Trainee',
            'VP/AVP/DGM/GM/AGM', 'Writer',
        ],
        '18. Scientist' => ['Scientist/Researcher'],
        '19. Services' => ['Civil Service', 'Defence', 'Govt.Service', 'Paramilitary', 'Police'],
        '20. Top Management' => ['CXO/President/Director/Chairman', 'Entrepreneur'],
    ],

    'how_did_you_hear_list' => [
        'Branding' => ['Auto', 'Bill Board', 'Boat', 'Bus', 'Metro'],
        'Event/Activity' => ['Carnival', 'Consumer Fair', 'Conventions'],
        'Magazine Ads' => ['Anugraha Magazine', 'College Magazines', 'Jeevadeepthi', 'Other Magazines', 'Parish Bulletins', 'Vanitha'],
        'Newspaper Ads' => ['Deepika', 'Deshabhimani', 'Janapraksham', 'Keralasabha'],
        'Others' => ['Hoarding', 'Notice/Pamphlet', 'Others', 'Tele-In', 'Telemarketing'],
        'Radio' => ['Aakashavani', 'Club FM', 'Local Radios', 'Radio Mango', 'Radio Mirchi', 'Red FM'],
        'Referral' => ['Church', 'Family', 'Family Marriage', 'Friends'],
        'Search Engine' => ['Bing', 'DuckDuckGo', 'Google Search', 'Yahoo', 'Yandex'],
        'Social Media' => ['Facebook', 'Instagram', 'LinkedIn', 'Pinterest', 'Snapchat', 'YouTube'],
        'TV Ads' => ['24news', 'Asianet', 'Asianet Movies', 'Asianet News', 'Flowers'],
    ],

    'language_list' => [
        'English', 'Hindi', 'Kannada', 'Konkani', 'Malayalam', 'Marathi', 'Tamil', 'Telugu', 'Tulu',
        'Bengali', 'Gujarati', 'Punjabi', 'Urdu', 'French', 'German', 'Spanish', 'Arabic',
    ],

    'eating_habits' => ['Vegetarian', 'Non-Vegetarian', 'Eggetarian', 'Vegan'],
    'drinking_habits' => ['No', 'Yes', 'Socially'],
    'smoking_habits' => ['No', 'Yes', 'Occasionally'],

    'cultural_background_list' => ['Traditional', 'Moderate', 'Modern', 'Liberal'],

    'hobbies_list' => [
        'Cooking', 'Nature', 'Dancing', 'Painting', 'Pets', 'Photography', 'Puzzles',
        'Gardening', 'Art / Handicraft', 'Listening to Music', 'Movies', 'Internet Surfing', 'Traveling',
    ],

    'music_list' => ['Film Songs', 'Indian / Classical Music', 'Western Music'],

    'books_list' => ['Biographies', 'Classic Literature', 'Comics', 'History', 'Magazines', 'Philosophy / Spiritual', 'Short Stories'],

    'movies_list' => ['Action', 'Comedy', 'Drama', 'Romance', 'Horror', 'Classics', 'Documentaries', 'Thriller', 'World Cinema'],

    'sports_list' => [
        'Badminton', 'Basketball', 'Cricket', 'Cycling', 'Football', 'Jogging / Walking',
        'Swimming', 'Tennis', 'Volleyball', 'Yoga / Meditation', 'Gym / Fitness', 'Carrom', 'Chess',
    ],

    'cuisine_list' => ['South Indian', 'North Indian', 'Chinese', 'Italian', 'Continental', 'Thai', 'Mexican', 'Arabic'],

    'jamath_list' => [
        'Sunni - EK', 'Sunni - AP', 'Mujahid (KNM)', 'Mujahid (Markaz)', 'Jamaat-e-Islami', 'Tableegh', 'Ahle Hadees',
        'Bohra', 'Khoja', 'Pathan', 'Syed', 'Sheikh', 'Other',
    ],

    // Country phone codes: [name, dial_code, iso2, flag_emoji]
    'phone_codes' => [
        // ── Frequently Used ──
        ['India', '+91', 'IN', "\u{1F1EE}\u{1F1F3}"],
        ['USA', '+1', 'US', "\u{1F1FA}\u{1F1F8}"],
        ['UAE', '+971', 'AE', "\u{1F1E6}\u{1F1EA}"],
        ['United Kingdom', '+44', 'GB', "\u{1F1EC}\u{1F1E7}"],
        ['Canada', '+1', 'CA', "\u{1F1E8}\u{1F1E6}"],
        ['Australia', '+61', 'AU', "\u{1F1E6}\u{1F1FA}"],
        ['Saudi Arabia', '+966', 'SA', "\u{1F1F8}\u{1F1E6}"],
        ['Qatar', '+974', 'QA', "\u{1F1F6}\u{1F1E6}"],
        ['New Zealand', '+64', 'NZ', "\u{1F1F3}\u{1F1FF}"],
        ['Oman', '+968', 'OM', "\u{1F1F4}\u{1F1F2}"],
        ['Singapore', '+65', 'SG', "\u{1F1F8}\u{1F1EC}"],
        ['Switzerland', '+41', 'CH', "\u{1F1E8}\u{1F1ED}"],
        ['Bahrain', '+973', 'BH', "\u{1F1E7}\u{1F1ED}"],
        ['France', '+33', 'FR', "\u{1F1EB}\u{1F1F7}"],
        ['Germany', '+49', 'DE', "\u{1F1E9}\u{1F1EA}"],
        ['Ireland', '+353', 'IE', "\u{1F1EE}\u{1F1EA}"],
        ['Italy', '+39', 'IT', "\u{1F1EE}\u{1F1F9}"],
        ['Kuwait', '+965', 'KW', "\u{1F1F0}\u{1F1FC}"],
        ['Malta', '+356', 'MT', "\u{1F1F2}\u{1F1F9}"],
        ['Malaysia', '+60', 'MY', "\u{1F1F2}\u{1F1FE}"],
        // ── Other Countries ──
        ['Afghanistan', '+93', 'AF', "\u{1F1E6}\u{1F1EB}"],
        ['Albania', '+355', 'AL', "\u{1F1E6}\u{1F1F1}"],
        ['Algeria', '+213', 'DZ', "\u{1F1E9}\u{1F1FF}"],
        ['Argentina', '+54', 'AR', "\u{1F1E6}\u{1F1F7}"],
        ['Austria', '+43', 'AT', "\u{1F1E6}\u{1F1F9}"],
        ['Bangladesh', '+880', 'BD', "\u{1F1E7}\u{1F1E9}"],
        ['Belgium', '+32', 'BE', "\u{1F1E7}\u{1F1EA}"],
        ['Bhutan', '+975', 'BT', "\u{1F1E7}\u{1F1F9}"],
        ['Brazil', '+55', 'BR', "\u{1F1E7}\u{1F1F7}"],
        ['Brunei', '+673', 'BN', "\u{1F1E7}\u{1F1F3}"],
        ['Cambodia', '+855', 'KH', "\u{1F1F0}\u{1F1ED}"],
        ['China', '+86', 'CN', "\u{1F1E8}\u{1F1F3}"],
        ['Colombia', '+57', 'CO', "\u{1F1E8}\u{1F1F4}"],
        ['Cyprus', '+357', 'CY', "\u{1F1E8}\u{1F1FE}"],
        ['Czech Republic', '+420', 'CZ', "\u{1F1E8}\u{1F1FF}"],
        ['Denmark', '+45', 'DK', "\u{1F1E9}\u{1F1F0}"],
        ['Egypt', '+20', 'EG', "\u{1F1EA}\u{1F1EC}"],
        ['Ethiopia', '+251', 'ET', "\u{1F1EA}\u{1F1F9}"],
        ['Fiji', '+679', 'FJ', "\u{1F1EB}\u{1F1EF}"],
        ['Finland', '+358', 'FI', "\u{1F1EB}\u{1F1EE}"],
        ['Ghana', '+233', 'GH', "\u{1F1EC}\u{1F1ED}"],
        ['Greece', '+30', 'GR', "\u{1F1EC}\u{1F1F7}"],
        ['Hong Kong', '+852', 'HK', "\u{1F1ED}\u{1F1F0}"],
        ['Hungary', '+36', 'HU', "\u{1F1ED}\u{1F1FA}"],
        ['Iceland', '+354', 'IS', "\u{1F1EE}\u{1F1F8}"],
        ['Indonesia', '+62', 'ID', "\u{1F1EE}\u{1F1E9}"],
        ['Iran', '+98', 'IR', "\u{1F1EE}\u{1F1F7}"],
        ['Iraq', '+964', 'IQ', "\u{1F1EE}\u{1F1F6}"],
        ['Israel', '+972', 'IL', "\u{1F1EE}\u{1F1F1}"],
        ['Japan', '+81', 'JP', "\u{1F1EF}\u{1F1F5}"],
        ['Jordan', '+962', 'JO', "\u{1F1EF}\u{1F1F4}"],
        ['Kazakhstan', '+7', 'KZ', "\u{1F1F0}\u{1F1FF}"],
        ['Kenya', '+254', 'KE', "\u{1F1F0}\u{1F1EA}"],
        ['South Korea', '+82', 'KR', "\u{1F1F0}\u{1F1F7}"],
        ['Lebanon', '+961', 'LB', "\u{1F1F1}\u{1F1E7}"],
        ['Libya', '+218', 'LY', "\u{1F1F1}\u{1F1FE}"],
        ['Luxembourg', '+352', 'LU', "\u{1F1F1}\u{1F1FA}"],
        ['Maldives', '+960', 'MV', "\u{1F1F2}\u{1F1FB}"],
        ['Mauritius', '+230', 'MU', "\u{1F1F2}\u{1F1FA}"],
        ['Mexico', '+52', 'MX', "\u{1F1F2}\u{1F1FD}"],
        ['Morocco', '+212', 'MA', "\u{1F1F2}\u{1F1E6}"],
        ['Myanmar', '+95', 'MM', "\u{1F1F2}\u{1F1F2}"],
        ['Nepal', '+977', 'NP', "\u{1F1F3}\u{1F1F5}"],
        ['Netherlands', '+31', 'NL', "\u{1F1F3}\u{1F1F1}"],
        ['Nigeria', '+234', 'NG', "\u{1F1F3}\u{1F1EC}"],
        ['Norway', '+47', 'NO', "\u{1F1F3}\u{1F1F4}"],
        ['Pakistan', '+92', 'PK', "\u{1F1F5}\u{1F1F0}"],
        ['Palestine', '+970', 'PS', "\u{1F1F5}\u{1F1F8}"],
        ['Peru', '+51', 'PE', "\u{1F1F5}\u{1F1EA}"],
        ['Philippines', '+63', 'PH', "\u{1F1F5}\u{1F1ED}"],
        ['Poland', '+48', 'PL', "\u{1F1F5}\u{1F1F1}"],
        ['Portugal', '+351', 'PT', "\u{1F1F5}\u{1F1F9}"],
        ['Romania', '+40', 'RO', "\u{1F1F7}\u{1F1F4}"],
        ['Russia', '+7', 'RU', "\u{1F1F7}\u{1F1FA}"],
        ['South Africa', '+27', 'ZA', "\u{1F1FF}\u{1F1E6}"],
        ['Spain', '+34', 'ES', "\u{1F1EA}\u{1F1F8}"],
        ['Sri Lanka', '+94', 'LK', "\u{1F1F1}\u{1F1F0}"],
        ['Sudan', '+249', 'SD', "\u{1F1F8}\u{1F1E9}"],
        ['Sweden', '+46', 'SE', "\u{1F1F8}\u{1F1EA}"],
        ['Taiwan', '+886', 'TW', "\u{1F1F9}\u{1F1FC}"],
        ['Tanzania', '+255', 'TZ', "\u{1F1F9}\u{1F1FF}"],
        ['Thailand', '+66', 'TH', "\u{1F1F9}\u{1F1ED}"],
        ['Turkey', '+90', 'TR', "\u{1F1F9}\u{1F1F7}"],
        ['Uganda', '+256', 'UG', "\u{1F1FA}\u{1F1EC}"],
        ['Ukraine', '+380', 'UA', "\u{1F1FA}\u{1F1E6}"],
        ['Vietnam', '+84', 'VN', "\u{1F1FB}\u{1F1F3}"],
        ['Yemen', '+967', 'YE', "\u{1F1FE}\u{1F1EA}"],
        ['Zimbabwe', '+263', 'ZW', "\u{1F1FF}\u{1F1FC}"],
    ],
];
